import { useState, useEffect, useRef } from 'react';
import { useSearchParams } from 'react-router';
import { Search, CheckCircle2, XCircle, ChevronRight, FileText, AlertCircle, Upload, Loader2, Camera, X, Shield } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { certificateApi } from '../lib/api/certificates';
import { Button } from '../components/ui/button';
import { toast } from 'sonner';

export function VerifyCertificatePage() {
  const [searchParams] = useSearchParams();
  const [certId, setCertId] = useState('');
  const [isVerifying, setIsVerifying] = useState(false);
  const [error, setError] = useState('');
  const [result, setResult] = useState<any>(null);
  const [uploadMode, setUploadMode] = useState(false);
  const [uploadedFile, setUploadedFile] = useState<File | null>(null);
  const [isExtracting, setIsExtracting] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  // ── Auto-verify from QR code link ──
  useEffect(() => {
    const idFromUrl = searchParams.get('certId');
    if (idFromUrl && idFromUrl.trim()) {
      setCertId(idFromUrl.trim());
      // Auto-trigger verification
      handleVerify(undefined, idFromUrl.trim());
    }
  }, [searchParams]);

  const handleVerify = async (e?: React.FormEvent, overrideId?: string) => {
    e?.preventDefault();
    const idToVerify = (overrideId || certId).trim();
    if (!idToVerify) return;

    setIsVerifying(true);
    setError('');
    setResult(null);

    try {
      const resp: any = await certificateApi.verifyCertificate(idToVerify);
      if (resp.success && resp.data) {
        setResult(resp.data);
      } else {
        setError('Certificate not found or invalid format.');
      }
    } catch (err: any) {
      setError(err?.message || 'Certificate not found. Please double-check the ID.');
    } finally {
      setIsVerifying(false);
    }
  };

  // ── Upload to Verify: Extract text from PDF/image ──
  const handleFileUpload = async (file: File) => {
    setUploadedFile(file);
    setIsExtracting(true);
    setError('');
    setResult(null);

    try {
      // Strategy: Read the file and search for certificate ID patterns
      const text = await extractTextFromFile(file);
      
      // Look for known certificate ID patterns
      const patterns = [
        /80G-[a-zA-Z0-9]+/i,
        /DON-[a-zA-Z0-9]+/i,
        /VOL-[a-zA-Z0-9]+/i,
        /CAMP-[a-zA-Z0-9]+/i,
        /PTR-[a-zA-Z0-9]+/i,
        /Certificate\s*ID:\s*([A-Za-z0-9-]+)/i,
      ];

      let foundId = '';
      for (const pattern of patterns) {
        const match = text.match(pattern);
        if (match) {
          foundId = match[0].replace(/Certificate\s*ID:\s*/i, '').trim();
          break;
        }
      }

      if (foundId) {
        setCertId(foundId);
        toast.success(`Found Certificate ID: ${foundId}`);
        // Auto-verify
        await handleVerify(undefined, foundId);
      } else {
        setError('Could not find a certificate ID in the uploaded file. Please enter it manually.');
      }
    } catch (err) {
      console.error('File extraction error:', err);
      setError('Failed to process the uploaded file. Please enter the certificate ID manually.');
    } finally {
      setIsExtracting(false);
    }
  };

  /** Extract text content from a PDF or image file */
  async function extractTextFromFile(file: File): Promise<string> {
    if (file.type === 'application/pdf') {
      // Read PDF as text - PDFs generated by pdfkit have embedded text
      const buffer = await file.arrayBuffer();
      const bytes = new Uint8Array(buffer);
      // Simple text extraction from PDF binary (works for text-based PDFs)
      let text = '';
      for (let i = 0; i < bytes.length; i++) {
        const char = bytes[i];
        if (char >= 32 && char <= 126) {
          text += String.fromCharCode(char);
        } else {
          text += ' ';
        }
      }
      return text;
    }
    
    // For images, try reading the filename for clues
    return file.name;
  }

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    const file = e.dataTransfer.files[0];
    if (file && (file.type === 'application/pdf' || file.type.startsWith('image/'))) {
      handleFileUpload(file);
    } else {
      toast.error('Please upload a PDF or image file');
    }
  };

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) handleFileUpload(file);
  };

  return (
    <div className="min-h-[calc(100vh-64px)] bg-[#FAF8F5] pt-16 pb-24">
      {/* Decorative Background */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none z-0">
        <div className="absolute top-[-10%] right-[-5%] w-[500px] h-[500px] rounded-full bg-[var(--womb-forest)] opacity-[0.03] blur-[100px]" />
        <div className="absolute bottom-[-10%] left-[-5%] w-[400px] h-[400px] rounded-full bg-[var(--journey-saffron)] opacity-[0.03] blur-[80px]" />
      </div>

      <div className="relative z-10 max-w-4xl mx-auto px-4 sm:px-6">
        {/* Header */}
        <div className="text-center mb-12">
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-white border border-gray-200 text-xs font-bold uppercase tracking-widest text-[var(--womb-forest)] mb-4 shadow-sm"
          >
            <Shield className="h-4 w-4" />
            Document Verification
          </motion.div>
          <motion.h1
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="text-4xl md:text-5xl font-black text-gray-900 tracking-tight mb-4"
          >
            Verify a <span className="text-[var(--womb-forest)]">Certificate</span>
          </motion.h1>
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="text-lg text-gray-600 max-w-2xl mx-auto"
          >
            Enter the Certificate ID, scan the QR code, or upload the document to verify its authenticity.
          </motion.p>
        </div>

        {/* Verification Methods Toggle */}
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ delay: 0.25 }}
          className="flex justify-center mb-6"
        >
          <div className="inline-flex p-1 bg-white rounded-2xl border border-gray-200 shadow-sm">
            <button
              onClick={() => setUploadMode(false)}
              className={`px-5 py-2.5 rounded-xl text-sm font-bold transition-all duration-300 flex items-center gap-2 ${
                !uploadMode
                  ? 'bg-[var(--womb-forest)] text-white shadow-md'
                  : 'text-gray-500 hover:text-gray-700'
              }`}
            >
              <Search className="h-4 w-4" /> Enter ID
            </button>
            <button
              onClick={() => setUploadMode(true)}
              className={`px-5 py-2.5 rounded-xl text-sm font-bold transition-all duration-300 flex items-center gap-2 ${
                uploadMode
                  ? 'bg-[var(--womb-forest)] text-white shadow-md'
                  : 'text-gray-500 hover:text-gray-700'
              }`}
            >
              <Upload className="h-4 w-4" /> Upload Certificate
            </button>
          </div>
        </motion.div>

        {/* Search / Upload Card */}
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ delay: 0.3 }}
          className="bg-white rounded-3xl shadow-xl border border-gray-100 p-6 md:p-10 mb-8"
        >
          <AnimatePresence mode="wait">
            {!uploadMode ? (
              <motion.div
                key="search"
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: 20 }}
                transition={{ duration: 0.3 }}
              >
                <form onSubmit={handleVerify} className="flex flex-col md:flex-row gap-4">
                  <div className="relative flex-1">
                    <Search className="absolute left-4 top-1/2 -translate-y-1/2 h-5 w-5 text-gray-400" />
                    <input
                      type="text"
                      placeholder="e.g. 80G-clxxx... or DON-ABCDEF12"
                      value={certId}
                      onChange={(e) => setCertId(e.target.value)}
                      className="w-full pl-12 pr-4 py-4 rounded-xl border-2 border-gray-200 focus:border-[var(--womb-forest)] focus:ring-4 focus:ring-[var(--womb-forest)]/10 outline-none text-lg font-medium tracking-wide placeholder:normal-case placeholder:tracking-normal transition-all"
                      required
                    />
                  </div>
                  <Button
                    type="submit"
                    size="lg"
                    disabled={isVerifying || !certId.trim()}
                    className="py-6 px-10 text-lg rounded-xl shadow-lg bg-[var(--womb-forest)] hover:bg-[var(--womb-forest)]/90 text-white min-w-[200px]"
                  >
                    {isVerifying ? (
                      <span className="flex items-center gap-2">
                        <Loader2 className="h-5 w-5 animate-spin" />
                        Verifying...
                      </span>
                    ) : (
                      <span className="flex items-center gap-2">
                        Verify Now <ChevronRight className="h-5 w-5" />
                      </span>
                    )}
                  </Button>
                </form>

                {/* Validation Guidelines */}
                <div className="mt-6 flex flex-wrap gap-4 text-xs font-medium text-gray-500 justify-center">
                  <span className="flex items-center gap-1.5"><div className="w-1.5 h-1.5 rounded-full bg-emerald-400" /> 80G Tax (80G-)</span>
                  <span className="flex items-center gap-1.5"><div className="w-1.5 h-1.5 rounded-full bg-blue-400" /> Donation (DON-)</span>
                  <span className="flex items-center gap-1.5"><div className="w-1.5 h-1.5 rounded-full bg-purple-400" /> Volunteer (VOL-)</span>
                  <span className="flex items-center gap-1.5"><div className="w-1.5 h-1.5 rounded-full bg-amber-400" /> Partner (PTR-)</span>
                  <span className="flex items-center gap-1.5"><div className="w-1.5 h-1.5 rounded-full bg-rose-400" /> Camp (CAMP-)</span>
                </div>
              </motion.div>
            ) : (
              <motion.div
                key="upload"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                transition={{ duration: 0.3 }}
              >
                {/* Upload Zone */}
                <div
                  onDragOver={(e) => e.preventDefault()}
                  onDrop={handleDrop}
                  onClick={() => fileInputRef.current?.click()}
                  className={`relative border-2 border-dashed rounded-2xl p-12 text-center cursor-pointer transition-all duration-300 group ${
                    uploadedFile
                      ? 'border-[var(--womb-forest)]/30 bg-[var(--womb-forest)]/[0.02]'
                      : 'border-gray-300 hover:border-[var(--womb-forest)]/50 hover:bg-[var(--womb-forest)]/[0.02]'
                  }`}
                >
                  <input
                    ref={fileInputRef}
                    type="file"
                    accept=".pdf,image/*"
                    onChange={handleFileSelect}
                    className="hidden"
                  />
                  
                  {isExtracting ? (
                    <div className="flex flex-col items-center gap-4">
                      <div className="w-16 h-16 rounded-2xl bg-[var(--womb-forest)]/10 flex items-center justify-center">
                        <Loader2 className="h-8 w-8 text-[var(--womb-forest)] animate-spin" />
                      </div>
                      <div>
                        <p className="text-lg font-bold text-gray-900">Analyzing Certificate...</p>
                        <p className="text-sm text-gray-500 mt-1">Extracting certificate ID from your document</p>
                      </div>
                    </div>
                  ) : uploadedFile ? (
                    <div className="flex flex-col items-center gap-4">
                      <div className="w-16 h-16 rounded-2xl bg-emerald-50 flex items-center justify-center">
                        <FileText className="h-8 w-8 text-emerald-600" />
                      </div>
                      <div>
                        <p className="text-lg font-bold text-gray-900">{uploadedFile.name}</p>
                        <p className="text-sm text-gray-500 mt-1">{(uploadedFile.size / 1024).toFixed(1)} KB</p>
                      </div>
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          setUploadedFile(null);
                          setResult(null);
                          setError('');
                        }}
                        className="text-xs text-red-500 hover:text-red-700 font-bold flex items-center gap-1"
                      >
                        <X className="h-3 w-3" /> Remove & try another
                      </button>
                    </div>
                  ) : (
                    <div className="flex flex-col items-center gap-4">
                      <div className="w-20 h-20 rounded-2xl bg-gray-100 group-hover:bg-[var(--womb-forest)]/10 flex items-center justify-center transition-colors duration-300">
                        <Upload className="h-10 w-10 text-gray-400 group-hover:text-[var(--womb-forest)] transition-colors duration-300" />
                      </div>
                      <div>
                        <p className="text-lg font-bold text-gray-900">
                          Drop your certificate here
                        </p>
                        <p className="text-sm text-gray-500 mt-1">
                          or <span className="text-[var(--womb-forest)] font-bold underline underline-offset-2">browse files</span> — supports PDF & images
                        </p>
                      </div>
                      <div className="flex items-center gap-3 text-[10px] font-bold text-gray-400 uppercase tracking-wider">
                        <span className="flex items-center gap-1"><Camera className="h-3 w-3" /> Photo of certificate</span>
                        <span>•</span>
                        <span className="flex items-center gap-1"><FileText className="h-3 w-3" /> Downloaded PDF</span>
                      </div>
                    </div>
                  )}
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </motion.div>

        {/* Results Area */}
        <AnimatePresence mode="wait">
          {error && (
            <motion.div
              key="error"
              initial={{ opacity: 0, y: 10, scale: 0.98 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="bg-red-50 border border-red-200 text-red-700 p-6 rounded-2xl flex items-start gap-4 mb-8"
            >
              <XCircle className="h-7 w-7 text-red-500 shrink-0 mt-0.5" />
              <div>
                <h3 className="font-bold text-lg mb-1">Verification Failed</h3>
                <p className="opacity-90 leading-relaxed text-sm">
                  {error} <br />
                  Please ensure the ID matches exactly what is printed on the certificate. Contact support if you believe this is an error.
                </p>
              </div>
            </motion.div>
          )}

          {result && !error && (
            <motion.div
              key="success"
              initial={{ opacity: 0, y: 10, scale: 0.98 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="bg-white rounded-3xl shadow-[0_8px_30px_rgb(0,0,0,0.04)] ring-1 ring-gray-100 overflow-hidden"
            >
              {/* Authentic Header Banner */}
              <div className="bg-gradient-to-r from-emerald-500 to-[var(--womb-forest)] px-8 py-5 text-white flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="h-12 w-12 bg-white/20 rounded-full flex items-center justify-center backdrop-blur-sm ring-2 ring-white/20">
                    <CheckCircle2 className="h-7 w-7 text-white" />
                  </div>
                  <div>
                    <h3 className="font-bold text-lg leading-tight tracking-wide">AUTHENTIC DOCUMENT</h3>
                    <p className="text-emerald-100 text-xs font-semibold uppercase tracking-wider">Verified by WombTo18 Foundation</p>
                  </div>
                </div>
                <div className="hidden sm:block text-right">
                  <div className="text-emerald-100 text-xs font-semibold uppercase tracking-wider mb-0.5">Certificate ID</div>
                  <div className="font-mono font-bold tracking-widest text-sm bg-white/10 px-3 py-1 rounded-lg">{result.certId}</div>
                </div>
              </div>

              {/* Verified Data */}
              <div className="p-8">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-x-12 gap-y-6">
                  <div>
                    <span className="block text-xs font-bold text-gray-400 uppercase tracking-wider mb-1">Recipient Name</span>
                    <span className="block text-xl font-bold text-gray-900">{result.recipientName}</span>
                  </div>
                  <div>
                    <span className="block text-xs font-bold text-gray-400 uppercase tracking-wider mb-1">Document Type</span>
                    <span className="block text-xl font-bold text-gray-900">{result.type}</span>
                  </div>
                  <div>
                    <span className="block text-xs font-bold text-gray-400 uppercase tracking-wider mb-1">Issue Date</span>
                    <span className="block text-lg font-bold text-gray-900">
                      {new Date(result.issueDate).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
                    </span>
                  </div>
                  <div>
                    <span className="block text-xs font-bold text-gray-400 uppercase tracking-wider mb-1">Verification Details</span>
                    <span className="block text-lg font-medium text-gray-700 leading-relaxed bg-gray-50 px-4 py-3 rounded-lg border border-gray-100">
                      {result.description}
                    </span>
                  </div>
                </div>

                {/* Verification timestamp */}
                <div className="mt-8 pt-6 border-t border-gray-100">
                  <div className="flex flex-col sm:flex-row gap-4">
                    <div className="flex items-start gap-3 bg-emerald-50/50 p-4 rounded-xl flex-1">
                      <CheckCircle2 className="h-5 w-5 text-emerald-500 shrink-0 mt-0.5" />
                      <div>
                        <p className="text-xs font-bold text-emerald-800 mb-0.5">Verification Successful</p>
                        <p className="text-[11px] text-emerald-600">
                          Verified on {new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })} at {new Date().toLocaleTimeString('en-IN')}
                        </p>
                      </div>
                    </div>
                    <div className="flex items-start gap-3 bg-blue-50/50 p-4 rounded-xl flex-1">
                      <AlertCircle className="h-5 w-5 text-blue-500 shrink-0 mt-0.5" />
                      <p className="text-xs text-blue-800 leading-relaxed font-medium">
                        This confirms the document was officially issued by WombTo18 Foundation. Any alteration after issuance invalidates it.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
